# Site settings
title: Scott Petit
email: petit.scott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random musings of an iOS Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottpet.it" # the base hostname & protocol for your site
twitter_username: ScottPetit
github_username:  ScottPetit

# Build settings
markdown: kramdown
