markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Scott Petit
url: http://scottpet.it
description: A fantastic blog that is fantastic.
twitter: ScottPetit
github: ScottPetit
gravatar_url: http://www.gravatar.com/avatar/30123dfd80ac9c7bd4d09816e7694dd2.png